name: Docker CI

on:
  push:
    tags: 
    - '[0-9]+.[0-9]+.[0-9]+-blanq'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set Tag
      run: echo "GITHUB_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    
    - name: Release name
      run: |
        echo "GITHUB_BASE_TAG=$(echo $GITHUB_TAG | cut -d'-' -f1)" >> $GITHUB_ENV
    
    - name: Lint Dockerfile
      run: |
        curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64 -o hadolint && chmod +x hadolint
        ./hadolint Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./
        push: true
        tags: |
          ${{ github.repository }}:${{ env.GITHUB_BASE_TAG}}
    
    - name: Status
      run: |
        echo "Release Tag - ${GITHUB_TAG}" >> ${GITHUB_STEP_SUMMARY}
        echo "Image Tag - ${GITHUB_BASE_TAG}" >> ${GITHUB_STEP_SUMMARY}
        echo "ğŸ Exited job with status - ${{ job.status }}"
